name: Pull request checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release/*

jobs:
  check-unique-standard-names:
    name: Check for duplicates in standard names
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libxml2-utils

      - name: Check for duplicate standard names
        run: |
          tools/check_xml_unique.py standard_names.xml

  check-name-rules:
    name: Check standard names against rules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libxml2-utils

      - name: Checks standard names against character rules
        run: |
          python3 tools/check_name_rules.py -s standard_names.xml

  test-rendering:
    name: Test rendering xml file to markdown and yaml
    needs: [check-unique-standard-names, check-name-rules]
    uses: ./.github/workflows/render.yml
    with:
      commit_to_branch: false
