name: Pull request precommit tasks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release/*
    types: [labeled]

jobs:

  render-and-commit:
    name: Rendering xml file to markdown and yaml, and commit to branch
    if: ${{ github.event.label.name == 'render-and-commit' }}
    uses: ./.github/workflows/render.yml
    with:
      commit_to_branch: true
    #runs-on: ubuntu-latest
    #steps:
    #  - name: Checkout repository
    #    uses: actions/checkout@v4
    #
    #  - name: Setup Python
    #    uses: actions/setup-python@v4
    #    with:
    #      python-version: "3.x"
    #
    #  - name: Install dependencies
    #    run: |
    #      sudo apt-get update
    #      sudo apt-get -y install libxml2-utils
    #      python -m pip install --upgrade pip
    #      python -m pip install PyYaml
    #
    #  - name: Test rendering xml file to markdown
    #    run: |
    #      tools/write_standard_name_table.py --output-format md standard_names.xml
    #      echo "The following changes will be committed when this pull request is merged (git diff Metadata-standard-names.md; "
    #      echo "assuming that 'Metadata-standard-names.md' wasn't updated and matches the version in the authoritative branch):"
    #      git diff Metadata-standard-names.md
    #
    #  - name: Test rendering xml file to yaml
    #    run: |
    #      tools/write_standard_name_table.py --output-format yaml standard_names.xml
    #      echo "The following changes will be committed when this pull request is merged (git diff Metadata-standard-names.yaml; "
    #      echo "assuming that 'Metadata-standard-names.yaml' wasn't updated and matches the version in the authoritative branch):"
    #      git diff Metadata-standard-names.yaml
