name: Pull request checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release/*

jobs:
  check-unique-standard-names:
    name: Check for duplicates in standard names
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libxml2-utils

      - name: Check for duplicate standard names
        run: |
          tools/check_xml_unique.py standard_names.xml

  check-name-rules:
    name: Check standard names against rules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libxml2-utils

      - name: Checks standard names against character rules
        run: |
          python3 tools/check_name_rules.py -s standard_names.xml

  test-rendering:
    name: Test rendering xml file to markdown and yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libxml2-utils
          python -m pip install --upgrade pip
          python -m pip install PyYaml

      - name: Test rendering xml file to markdown
        run: |
          # Checks if the saved markdown matches freshly rendered markdown.
          # If this fails, prompt user to update
          tools/write_standard_name_table.py --output-format md standard_names.xml
          if ! git diff --exit-code --quiet; then
            echo "❌ Detected that Metadata-standard-names.md is not consistent with standard_names.xml"
            echo "✅ To fix: Run the following command locally and commit the result:"
            echo "    tools/write_standard_name_table.py --output-format md standard_names.xml"
            echo "📘 This script requires the pyyaml Python package; to install with pip use command:"
            echo "    python -m pip install PyYaml"
            echo "📘 For conda users, environment file tools/environment.yml is provided."
            echo
            exit 1
          fi

      - name: Test rendering xml file to yaml
        run: |
          tools/write_standard_name_table.py --output-format yaml standard_names.xml
          if ! git diff --exit-code --quiet; then
            echo "❌ Detected that Metadata-standard-names.yaml is not consistent with standard_names.xml"
            echo "✅ To fix: Run the following command locally and commit the result:"
            echo "    tools/write_standard_name_table.py --output-format yaml standard_names.xml"
            echo "📘 This script requires the pyyaml Python package; to install with pip use command:"
            echo "    python -m pip install PyYaml"
            echo "📘 For conda users, environment file tools/environment.yml is provided."
            echo
            exit 1
          fi

