name: Pull request precommit tasks

on:
  # This workflow is only valid for pull_request events
  #workflow_dispatch:
  pull_request:
    branches:
      - main
      - release/*
    types: [labeled]

jobs:

  render-and-commit:
    name: Rendering xml file to markdown and yaml, and commit to branch
    if: ${{ github.event.label.name == 'render-and-commit' }}
    uses: ./.github/workflows/render.yml
    with:
      commit_to_branch: true
      # github.head_ref is the branch from which a pull request is made
      branch_name: ${{ github.head_ref }}
      # github.event.pull_request.head.repo.clone_url is the URL from where the pull request is made
      remote_url: ${{ github.event.pull_request.head.repo.clone_url }}
